### ISSUE TITLE
Authentication failure with GovCloud

### ISSUE THREAD

**Issue by peterdeme** [hashicorp/packer-plugin-amazon#338]
#### Overview of the Issue

While working with non-GovCloud seem to work perfectly fine, whenever I switch my credentials to Govcloud the build starts to fail. The interesting thing here is that the AWS CLI works perfectly fine. Packer on the other hand seem to have authentication issues. Any ideas?

Receiving the following error:
```
Build 'amazon-ebs.spacelift' errored after 172 milliseconds 540 microseconds: error validating regions: AuthFailure: AWS was not able to validate the provided access credentials
```

#### Reproduction Steps

```yaml
jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    name: Build the AWS AMI using Packer
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out the source code
        uses: actions/checkout@main

      - name: Configure GovCloud credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-gov-east-1
          role-to-assume: arn:aws-us-gov:iam::<account-id>:role/<role-name>
          role-duration-seconds: 3600

      - name: Setup packer
        uses: hashicorp/setup-packer@main

      - name: test credentials
        run: |
          aws ec2 describe-regions

      - name: Init packer
        run: packer init aws.pkr.hcl

      - name: Build with packer
        run: packer build -debug aws.pkr.hcl
        env:
          PACKER_LOG: 1
          PKR_VAR_ami_regions: '["us-gov-east-1", "us-gov-west-1"]'
```

### Plugin and Packer version

1.8.6

### Simplified Packer Buildfile
```
source "amazon-ebs" "spacelift" {
  source_ami_filter {
      filters = {
        virtualization-type = "hvm"
        name                = "amzn2-ami-kernel-5.10-hvm-2*-gp2"
        root-device-type    = "ebs"
        architecture        = var.source_ami_architecture
      }
      owners      = var.source_ami_owners
      most_recent = true
  }

  ami_name    = "${var.ami_name_prefix}-${var.source_ami_architecture}"
  ami_regions = var.ami_regions
  ami_groups  = var.ami_groups

  shared_credentials_file = var.shared_credentials_file
  encrypt_boot            = var.encrypt_boot
  instance_type           = var.instance_type
  ssh_username            = "ec2-user"

  vpc_id = var.vpc_id
  region = var.region

  dynamic "subnet_filter" {
    for_each = var.subnet_filter == null ? [] : [1]
    content {
      filters   = var.subnet_filter
      most_free = true
      random    = false
    }
  }
)
}

build {
  sources = ["source.amazon-ebs.spacelift"]
}
```

### Operating system and Environment details

GitHub Actions, `ubuntu-latest`

### Log Fragments and crash.log files

```
# This is a previous step I added for testing:

Run aws ec2 describe-regions
{
    "Regions": [
        {
            "Endpoint": "ec2.us-gov-west-1.amazonaws.com",
            "RegionName": "us-gov-west-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.us-gov-east-1.amazonaws.com",
            "RegionName": "us-gov-east-1",
            "OptInStatus": "opt-in-not-required"
        }
    ]
}

# Actual packer logs:
Run packer build -debug aws.pkr.hcl
  packer build -debug aws.pkr.hcl
  shell: /usr/bin/bash -e {0}
  env:
    AWS_DEFAULT_REGION: us-gov-east-1
    AWS_REGION: us-gov-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    PACKER_LOG: 1
    PKR_VAR_ami_regions: ["us-gov-east-1", "us-gov-west-1"]
    PKR_VAR_source_ami_architecture: arm64
    PKR_VAR_instance_type: t4g.micro
[...]
2023/03/01 15:03:04 Running builder: 
2023/03/01 15:03:04 [INFO] (telemetry) Starting builder amazon-ebs.spacelift

2023/03/01 15:03:04 packer-builder-amazon-ebs plugin: [INFO] AWS Auth provider used: "EnvProvider"
2023/03/01 15:03:04 packer-builder-amazon-ebs plugin: Found region us-east-1
2023/03/01 15:03:04 packer-builder-amazon-ebs plugin: [INFO] AWS Auth provider used: "EnvProvider"
2023/03/01 15:03:04 [INFO] (telemetry) ending amazon-ebs.spacelift
Build 'amazon-ebs.spacelift' errored after 172 milliseconds 540 microseconds: error validating regions: AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: 8cc5f9ff-b0da-495c-9f1b-bb00f1dcbace
	status code: 401, request id: 8cc5f9ff-b0da-495c-9f1b-bb00f1dcbace

==> Wait completed after 173 milliseconds 28 microseconds
```
